# Permalinks
permalink:        pretty

# Setup
title:            Adri
tagline:          'My blog, re-invented'
description:      'A blog mostly about mobile development in Swift, with occasional rumblings in other subjects'
url:              https://amg1976.github.io

author:
  name:           'Adriano Goncalves'
  url:            https://twitter.com/amg1976

paginate:         1
paginate_path:    "/blog/page:num/"

jekyll-archives:
  enabled:
    - year
    - month
  layouts:
    year: archive-year
    month: archive-month
  permalinks:
    year: '/archives/:year/'
    month: '/archives/:year/:month/'

# Custom vars
version:          2.0.0
github:
  repo:           https://github.com/poole/hyde
